import Head from 'next/head'
import AboutPage from "../components/templates/AboutPage";

export default function About() {
  return (
    <>
    <Head>
      <title>About | Tuan Au Duong</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <AboutPage />
    </>
  )
}
