import Head from 'next/head'

export default function About() {
  return (
    <>
    <Head>
      <title>Blog | Tuan Au Duong</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <div className='main-container items-center justify-center'>
    <iframe src="https://giphy.com/embed/3o72FkiKGMGauydfyg" width="480" height="363" frameBorder="0" className="giphy-embed" allowFullScreen></iframe>

    </div>

    </>
  )
}
