import Head from 'next/head'
import BlogPage from '../components/templates/BlogPage'

export default function About() {
  return (
    <>
    <Head>
      <title>Blog | Tuan Au Duong</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <BlogPage />
    </>
  )
}
