import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import allProjects from '../lib/project'
import HomePage, {HomePageProps} from "../components/templates/HomePage";
import { useAppContext } from '../lib/context/AppContext';

export default function Index({posts, projects} : HomePageProps) {
  const appContext = useAppContext();
  return (
    <>
    <Head>
      <title>{appContext.webName}</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <HomePage projects={projects} posts={posts} />
    </>
  )
}
export async function getStaticProps() {
  return {
    props: {
      projects: allProjects
    }
  }
}