import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import {getAllPosts} from '../lib/post'
import allProjects from '../lib/project'
import HomePage, {HomePageProps} from "../components/templates/HomePage";

export default function Index({posts, projects} : HomePageProps) {
  return (
    <>
    <Head>
      <title>Tuan Au Duong</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <HomePage projects={projects} posts={posts} />
    </>
  )
}
export async function getStaticProps() {
  return {
    props: {
      posts: await getAllPosts(),
      projects: allProjects
    }
  }
}